config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :recipes
  resources :ingredients
  resources :quantities
  resources :home
  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role? :admin
      can :manage, :all
    elsif user.role? :registered
      can :create, [Recipe, Ingredient, Quantity]
      can :read, :all
      # can :update, Recipe do |recipe|
      #   recipe.creator == user
      # end
     can :update, Recipe, creator_id: user.id
   #  can :destroy, all.self 
    else
      can :read, [Recipe, Category, Ingredient, Quantity]
    end

  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :recipes

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: 2..255 }

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  has_many :quantities

  has_many :recipes, through: :quantities

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: 2..255 }

end

app/models/quantity.rb
class Quantity < ActiveRecord::Base

belongs_to :recipe
belongs_to :ingredient

# validates :amount, presence: true
# validates :amount, length: { in: 2..255 }

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  has_many :quantities

  has_many :ingredients, through: :quantities

  belongs_to :category
  belongs_to :creator, class_name: 'User'

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: 2..255 }

  validates :instructions, presence: true

end

app/models/role.rb
class Role < ActiveRecord::Base

  has_many :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role

  has_many :recipes, foreign_key: :creator_id

  before_create :set_default_role


  def role?(role_to_compare_to)
    role_to_compare_to.to_s == self.role.try(:name).to_s
  end

  private
  
  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path alert: "You do not have permission to do that"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  load_and_authorize_resource

  def index
    @categories = Category.all.order(:name)
  end

  def show
    @category = find_category
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.create(category_params)
    redirect_to(category_path(category.id))
  end

  def destroy
    category = find_category
    category.destroy
    redirect_to(categories_path)
  end

  def edit
    @category = find_category
  end

  def update
    category = find_category
    category.update(category_params)
    redirect_to(category_path(category.id))
  end

  private

  def find_category
    Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  load_and_authorize_resource

  def index
    @ingredients = Ingredient.all.order(:name)
  end

  def show
    @ingredient = find_ingredient
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    Ingredient.create(ingredient_params)
    redirect_to(ingredients_path)
  end

  def destroy
    ingredient = find_ingredient
    ingredient.destroy
    redirect_to(ingredients_path)
  end

  def edit
    @ingredient = find_ingredient
  end

  def update
    ingredient = find_ingredient
    ingredient.update(ingredient_params)
    redirect_to(ingredients_path)
  end

  private

  def find_ingredient
    Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController

  load_and_authorize_resource

  def index
    @quantities = Quantity.all 
  end

  def show
    @quantity = find_quantity
  end

  def new
    @quantity = Quantity.new
  end

  def create
    Quantity.create(quantity_params)
    redirect_to(quantities_path)
  end

  def destroy
    quantity = find_quantity
    quantity.destroy
    redirect_to(quantities_path)
  end

  def edit
    @quantity = find_quantity
  end

  def update
    quantity = find_quantity
    quantity.update(quantity_params)
    redirect_to(quantity_path(quantity.id))
  end

  private

  def find_quantity
    Quantity.find(params[:id])
  end

  def quantity_params
    params.require(:quantity).permit(:ingredient_id, :recipe_id, :amount)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  load_and_authorize_resource

  def index
    @recipes = Recipe.all.order(:name)
  end

  def show
    @recipe = find_recipe
  end

  def new
    @recipe = current_user.recipes.new
  end

  def create
    recipe = current_user.recipes.create(recipe_params)
    redirect_to( recipe_path( recipe.id ) )
  end

  def destroy
    recipe = find_recipe
    recipe.destroy
    redirect_to(recipes_path)
  end

  def edit
    @recipe = find_recipe
  end

  def update
    recipe = find_recipe
    recipe.update(recipe_params)
    redirect_to(recipe_path(recipe.id))
  end

  private

  def find_recipe
    Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :category_id, :vegetarian, :instructions, { ingredient_ids: [] })
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/views/categories/_category.html.erb
  <h2>
    <%= link_to("#{category.name}", category_path(category)) %>
  <%= link_to image_tag('http://i.imgur.com/PYI7y3E.png', size: "12", class: "imgbutton"), edit_category_path(category) if can? :edit, category %> <%= link_to image_tag('http://i.imgur.com/TZjRfjf.png', size: "12", class: 'imgbutton'), category_path(category), method: :delete, data:{confirm: 'Confirm Deleting'} if can? :destroy, category %>
  </h2>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
<%= f.label :name, "Category Name:", class: "formleft" %>
<%= f.text_field :name, class: "formright" %>
<br>
<br>
<center>
<div class='submitform'>
  <%= f.submit button_text, class: "button" %>
</div>
</center>
<% end %>

app/views/categories/_forshow.html.erb
<center> 
<br>
  <h2>
  <div class='headleft'>
    <%= link_to("Back", categories_path, class: "button") %>
  </div>
  <div class='headmid'>
    <%= @category.name %>
  </div>
    <div class='headright'>
      <%= link_to "Edit Category", edit_category_path(@category), class: "button" if can? :edit, @category %> <%= link_to 'Delete Category', category_path(@category), method: :delete, class: 'button', data:{confirm: 'Confirm Deleting'} if can? :destroy, @category %>
    </div>
  </h2>
  <br>
  <% @category.recipes.each do |recipe| %>
  <%= simple_format link_to(recipe.name, recipe_path(recipe)) %>
  <% end %>
</center>

app/views/categories/edit.html.erb
<center>
  <br>
  <br>
  <h2>Update Category</h2>
<br>
</center>
<%= render partial: "form", locals: {button_text: "Update Category"} %>

app/views/categories/index.html.erb
<center>
  <br>
  <br>
  <h1>Categories</h1>
  <br>
  <%= render @categories %>
</center>


<footer>
  <center>
    <%= link_to "Add Category", new_category_path, class: 'button' if can? :create, Category %>
  </center>
</footer>

app/views/categories/new.html.erb
<center>
  <br>
  <br>
  <h2>Adding Category</h2>
<br>
</center>
<%= render partial: "form", locals: {button_text: "Add Category"} %>

app/views/home/index.html.erb
<div class='content'>
<br>
<br>
<br>
<center>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<h2>Welcome to Simon's Cookbook App!</h2>
</center>
<p>Navigate about to see recipes.</p>
<p>Sign up or Sign in, to create new recipes!</p>
<br>
<p>Happy Cooking!</p>
</div>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
<%= f.label :name, "Ingredient Name:", class: "formleft" %>
<%= f.text_field :name, class: "formright" %>
<br>
<br>
<center>
<div class='submitform'>
  <%= f.submit button_text, class: "button" %>
</div>
</center>
<% end %>

app/views/ingredients/_forshow.html.erb
<center>
  <br>
  <h2>
  <div class='headleft'>
    <%= link_to("Back", ingredients_path, class: "button") %>
  </div>
  <div class='headmid'>
  <%= @ingredient.name %>
  </div>
  <div class='headright'>
    <%= link_to "Edit Ingredient", edit_ingredient_path(@ingredient), class: "button" if can? :edit, @ingredient %> <%= link_to 'Delete Ingredient', ingredient_path(@ingredient), method: :delete, class: 'button', data:{confirm: 'Confirm Deleting'} if can? :edit, @category %>
  </div>
  </h2>
  <br>
  <% @ingredient.recipes.each do |recipe| %>
  <%= simple_format link_to(recipe.name, recipe_path(recipe)) %>
  <% end %>
</center>

app/views/ingredients/_ingredient.html.erb
<h2>
  <%= link_to("#{ingredient.name}", ingredient_path(ingredient)) %>
  <%= link_to image_tag('http://i.imgur.com/PYI7y3E.png', size: "12", class: "imgbutton"), edit_ingredient_path(ingredient) if can? :edit, ingredient %> <%= link_to image_tag('http://i.imgur.com/TZjRfjf.png', size: "12", class: 'imgbutton'), ingredient_path(ingredient), method: :delete, data:{confirm: 'Confirm Deleting'} if can? :destroy, ingredient %>
</h2>

app/views/ingredients/edit.html.erb
<center>
  <br>
  <br>
  <h2>Editing Ingredient</h2>
<br>
</center>
<%= render partial: "form", locals: {button_text: "Update Ingredient"} %>

app/views/ingredients/index.html.erb
<center>
  <br>
  <br>
  <h1>Ingredients</h1>
  <br>
  <%= render @ingredients %>
</center>

<footer>
  <center>
    <%= link_to 'New Ingredient', new_ingredient_path, class: 'button' if can? :create, Ingredient %> <%= link_to 'Add Ingredient Measurement', new_quantity_path, class: 'button' if can? :create, Quantity %> <%= link_to("See All Measurements", quantities_path, class: "button") %>
  </center>
</footer>

app/views/ingredients/new.html.erb
<center>
  <br>
  <br>
  <h2>Adding Ingredient</h2>
<br>
</center>
<%= render partial: "form", locals: {button_text: "Add Ingredient"} %>

app/views/ingredients/show.html.erb
<br>
<%= render partial: "forshow" %>

app/views/layouts/_menu.html.erb
<nav>
  <ul>
    <li>
      <% if user_signed_in? %>
        <%= link_to 'logout', destroy_user_session_path, method: :delete, class: "button" %>
      <% else %>
        <%= link_to 'login', new_user_session_path, class: "button" %> | <%= link_to 'register', new_user_registration_path, class: "button" %>
      <% end %>
    </li>
    <li><%= link_to("Categories", categories_path, class: "button") %></li>
    <li><%= link_to("Recipes", recipes_path, class: "button") %></li>
    <li><%= link_to("Ingredients", ingredients_path, class: "button") %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookbookAppHw</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<div class='header-cont'>
  <header>
    <center>
      <img alt="CookBook App" src="http://i.imgur.com/aI0GGRW.png" />
      <%= render partial: "layouts/menu" %>
    </center>
    <br>
  </header>
</div>
<br>
<body>
  <div class='wrap'>
    <%= yield %>
  </div>
</body>

</html>

app/views/quantities/_form.html.erb
<%= form_for @quantity do |f| %>
<div class='mfleft'><%= f.label :recipe_id, "Recipe:" %></div>
<div class='mfright'>
<% if @quantity.persisted? %>
<%= @quantity.recipe.try(:name) %>
<% else %>
<%= f.collection_select :recipe_id, Recipe.all, :id, :name %>
<% end %>
</div>
<br>
<br>
<div class='mfleft'><%= f.label :ingredient_id, "Ingredient:" %></div>
<div class='mfright'><%= f.collection_select :ingredient_id, Ingredient.all, :id, :name %></div>
<br>
<br>
<div class='mfleft'><%= f.label :amount, "Amount:" %></div>
<div class='mfright'><%= f.text_field :amount, size: 70 %></div>
<br>
<br>
<center>
<div class='submitform'>
  <%= f.submit button_text, class: "button" %>
</div>
</center>
<% end %>

app/views/quantities/_forshow.html.erb
<center> 
  <br>
  <h2>
  <div class='headleft'>
    <%= link_to("Back", recipes_path, class: "button") %>
  </div>
    <%= @quantity.recipe.name %>
  <div class='headright'>
    <%= link_to("Edit Amount", edit_recipe_path(@quantity), class: "button") %> <%= button_to('Delete Amount', recipe_path(@quantity), method: :delete, class: 'button', data:{confirm: 'Confirm Deleting'}) %>
  </div>
  </h2>
</center>
<br>

app/views/quantities/_quantity.html.erb
<% @quantities.each do |q| %>
  <p> <%= q.recipe.name %> </p>
<% end %>
<br>

app/views/quantities/edit.html.erb
<center>
  <br>
  <br>
  <h2>Update Amount</h2>
<br>
</center>
<%= render partial: "form", locals: {button_text: "Update Amount"} %>

app/views/quantities/index.html.erb
<center>
  <br>
  <br>
  <h2>Recipe Ingredient Amounts</h2>
  <br>

  <% @quantities.each do |q| %>
    <%= q.amount %> <%= q.ingredient.try(:name) %> <%= link_to image_tag("http://i.imgur.com/TZjRfjf.png", size: '9', class: 'imgbutton'), quantity_path(q), method: :delete, data:{confirm: 'Confirm Deleting'} if can? :destroy, q %><br>
  <% end %>


</center>

<footer>
  <center>
    <%= link_to 'New Ingredient Amount', new_quantity_path, class: 'button' if can? :create, Quantity %>
  </center>
</footer>

app/views/quantities/new.html.erb
<center>
  <br>
  <br>
  <h2>Adding Amounts</h2>
<br>
</center>
<%= render partial: "form", locals: {button_text: "Add Amounts"} %>

app/views/quantities/show.html.erb
<br>
<%= render partial: "forshow" %>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
<div class='mfleft'><%= f.label :name, "Recipe Name:" %></div>
<div class='mfright'><%= f.text_field :name, size: 70 %></div>
<br>
<br>
<div class='mfleft'><%= f.label :category_id, "Category:" %></div>
<div class='mfright'><%= f.select :category_id, Category.all.map { |c| [c.name, c.id] } %></div>
<br>
<br>
<div class='mfleft'><%= f.label :vegetarian, "Vegetarian:" %></div>
<div class='mfright'><%= f.check_box :vegetarian %></div>
<br>
<br>

<div class='mfleft'><%= f.label :ingredient_ids, "Ingredients:" %></div>
<div class='mfright cb'><%= f.collection_check_boxes :ingredient_ids, Ingredient.all.order(:name), :id, :name %></div>
<br>
<br>
<br>
<br>
<br>
<div class='mfleft'><%= f.label :instructions, "Instructions:" %></div>
<div class='mfright'><%= f.text_area :instructions, size: "70x10" %></div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<center>
<div class='submitform'>
  <%= f.submit button_text, class: "button" %>
</div>
</center>
<% end %>

app/views/recipes/_forshow.html.erb
<center> 
  <br>
  <h2>
  <div class='headleft'>
    <%= link_to("Back", recipes_path, class: "button") %>
  </div>
  <div class='headmid'>
    <%= @recipe.name %>
  </div>
  <div class='headright'>
    <%= link_to "Edit Recipe", edit_recipe_path(@recipe), class: "button" if can? :edit, @recipe %> <%= link_to 'Delete Recipe', recipe_path(@recipe), method: :delete, class: 'button', data:{confirm: 'Confirm Deleting'} if can? :destroy, @recipe %>
  </div>
  </h2>
</center>
<br>
<br>
<br>
<div class='recipeleft'>
  <p><strong>Category:</strong> <%= link_to(@recipe.category.name, @recipe.category) if @recipe.category %></p>
  <p><strong>Vegetarian:</strong> <%= @recipe.vegetarian %></p>
  <p><strong>Ingredients:</strong> 
    <% @recipe.quantities.each do |quantity| %>
      <br>
      <%= quantity.amount %>
      <%= link_to(quantity.ingredient.name, quantity.ingredient) %>
      <%= link_to(image_tag('http://i.imgur.com/PYI7y3E.png', size: "9", class: "imgbutton"), edit_quantity_path(quantity)) %>
      <% end %>
  </p>
  </div>
  <br>
  <center>
    <strong>Instructions:</strong>
  </center>
  <div class='recipemain'>
    <%= @recipe.instructions %>
  </div>
  <br>
  <br>

app/views/recipes/_recipe.html.erb
<h2>
  <%= link_to("#{recipe.name} - #{recipe.category.try(:name)}", recipe_path(recipe)) %>
</h2>

app/views/recipes/edit.html.erb
<center>
  <br>
  <br>
  <h2>Update Recipe</h2>
<br>
</center>
<%= render partial: "form", locals: {button_text: "Update Recipe"} %>

app/views/recipes/index.html.erb
<center>
  <br>
  <br>
  <h1>Recipes</h1>
  <br>
  <%= render @recipes %>
</center>

<footer>
  <center>
    <%= link_to 'New Recipe', new_recipe_path, class: 'button' if can? :create, Recipe %>
  </center>
</footer>

app/views/recipes/new.html.erb
<center>
  <br>
  <br>
  <h2>Adding Recipes</h2>
<br>
</center>
<%= render partial: "form", locals: {button_text: "Add Recipe"} %>